### ISSUE TITLE
setting up an autoconf and automake file

### ISSUE THREAD

**Issue by andy5995** [cade-vs/vfu-dist#2]
https://github.com/cade-vs/vfu-dist/blob/036fe29881bde07605f104e16a3e1f97a005ac72/TODO#L8

I can set up an automake and autoconf file, which would provide a `./configure` script and Makefiles that are more portable than your current setup. I would need to go over a few details with you first before I start. Let me know if you're interested.

**Comment by cade-vs** [comment]
hello Andy and thanks for the fixes!

I was really surprised by the missing parens in the GO32 target (I haven't compiled for it since 90s :))
did you find it by compile or pure chance?

I merged all your PRs (have to cleanup CM_* and CB_* but for now it seems ok). 

About the autoconf/automake thing, I really wanted to avoid them and manage to use simple makefile to
compile under Linux, DOS/DJGPP/GO32, Cygwin, NetBSD, FreeBSD, Solaris, Plan9, Hurd, Maemo, so it kind-of
works (well, with explicit targets sometimes) :) I'm not strictly against autoconf/automake and if you 
think we might get something useful from it I'm fine to try it. In any case I'd like to keep current 
makefile option as well.

Again, thank you for your time and I'll be glad to help you if you have further issues with VFU or 
if you have questions, ideas, etc.!

Greetings,
Vladi.
--



On Mon, 24 Dec 2018 22:47:59 -0800
Andy Alt <notifications@github.com> wrote:

> https://github.com/cade-vs/vfu-dist/blob/036fe29881bde07605f104e16a3e1f97a005ac72/TODO#L8
> 
> I can set up an automake and autoconf file, which would provide a `./configure` script and Makefiles that are more portable than your current setup. I would need to go over a few details with you first before I start. Let me know if you're interested.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cade-vs/vfu-dist/issues/2


-- 
Vladi Belperchinov-Shabanski  
<cade@bis.bg> <cade@biscom.net> <cade@datamax.bg> http://cade.datamax.bg
pgp/gpg key 6F35B214 @ http://pgp.mit.edu

**Comment by andy5995** [comment]
> hello Andy and thanks for the fixes! I was really surprised by the missing parens in the GO32 target (I haven't compiled for it since 90s :)) did you find it by compile or pure chance? 

Using `cppcheck`. My compiler missed it. 

>I merged all your PRs (have to cleanup CM_* and CB_* but for now it seems ok). About the autoconf/automake thing, I really wanted to avoid them and manage to use simple makefile to compile under Linux, DOS/DJGPP/GO32, Cygwin, NetBSD, FreeBSD, Solaris, Plan9, Hurd, Maemo, so it kind-of works (well, with explicit targets sometimes) :) I'm not strictly against autoconf/automake and if you think we might get something useful from it I'm fine to try it. In any case I'd like to keep current makefile option as well.

I think it will only take me about 15 minutes. And yes, it can be done without touching your current makefile. I do think it will prove to be useful. I'll submit a PR for it, and if you decide you don't need it, you can always get rid of it later. ;)

vfu was my main file manager for some years, and glad to be able to help out now that my programming skills are more advanced.

**Comment by cade-vs** [comment]
On Fri, 28 Dec 2018 21:54:39 -0800
Andy Alt <notifications@github.com> wrote:

> > hello Andy and thanks for the fixes! I was really surprised by the missing parens in the GO32 target (I haven't compiled for it since 90s :)) did you find it by compile or pure chance? 
> 
> Using `cppcheck`. My compiler missed it. 


yes, it will miss it. I guess you will never have GO32 target, I even consider to remove it with all the connected source...
but will reconsider next year :)


> 
> >I merged all your PRs (have to cleanup CM_* and CB_* but for now it seems ok). About the autoconf/automake thing, I really wanted to avoid them and manage to use simple makefile to compile under Linux, DOS/DJGPP/GO32, Cygwin, NetBSD, FreeBSD, Solaris, Plan9, Hurd, Maemo, so it kind-of works (well, with explicit targets sometimes) :) I'm not strictly against autoconf/automake and if you think we might get something useful from it I'm fine to try it. In any case I'd like to keep current makefile option as well.
> 
> I think it will only take me about 15 minutes. And yes, it can be done without touching your current makefile. I do think it will prove to be useful. I'll submit a PR for it, and if you decide you don't need it, you can always get rid of it later. ;)
> 
> vfu was my main file manager for some years, and glad to be able to help out now that my programming skills are more advanced.
> 

it is wonderful you find it useful, also I can help as well if you have something missing in it or need sth new.

cheers!

> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/cade-vs/vfu-dist/issues/2#issuecomment-450468168


-- 
Vladi Belperchinov-Shabanski  
<cade@bis.bg> <cade@biscom.net> <cade@datamax.bg> http://cade.datamax.bg
pgp/gpg key 6F35B214 @ http://pgp.mit.edu

**Comment by andy5995** [comment]
> it is wonderful you find it useful, also I can help as well if you have something missing in it or need sth new. cheers!

I'll keep that in mind. What do you think about setting up a [Matrix](https://matrix.org/blog/home/) development chat room for vfu? It's what I've been using lately for some of my projects. I prefer it over IRC because I don't have to worry about missing messages if I'm not logged in all the time, and it's driven mostly by open source software, afaik.
